export namespace Flag {
  export const VOLTCODE_AUTO_SHARE = truthy("VOLTCODE_AUTO_SHARE")
  export const VOLTCODE_GIT_BASH_PATH = process.env["VOLTCODE_GIT_BASH_PATH"]
  export const VOLTCODE_PARENT_SESSION = process.env["VOLTCODE_PARENT_SESSION"]
  export const VOLTCODE_CONFIG = process.env["VOLTCODE_CONFIG"]
  export const VOLTCODE_CONFIG_DIR = process.env["VOLTCODE_CONFIG_DIR"]
  export const VOLTCODE_CONFIG_CONTENT = process.env["VOLTCODE_CONFIG_CONTENT"]
  export const VOLTCODE_DISABLE_AUTOUPDATE = truthy("VOLTCODE_DISABLE_AUTOUPDATE")
  export const VOLTCODE_DISABLE_PRUNE = truthy("VOLTCODE_DISABLE_PRUNE")
  export const VOLTCODE_DISABLE_TERMINAL_TITLE = truthy("VOLTCODE_DISABLE_TERMINAL_TITLE")
  export const VOLTCODE_PERMISSION = process.env["VOLTCODE_PERMISSION"]
  export const VOLTCODE_DISABLE_DEFAULT_PLUGINS = truthy("VOLTCODE_DISABLE_DEFAULT_PLUGINS")
  export const VOLTCODE_DISABLE_LSP_DOWNLOAD = truthy("VOLTCODE_DISABLE_LSP_DOWNLOAD")
  export const VOLTCODE_ENABLE_EXPERIMENTAL_MODELS = truthy("VOLTCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const VOLTCODE_DISABLE_AUTOCOMPACT = truthy("VOLTCODE_DISABLE_AUTOCOMPACT")
  export const VOLTCODE_DISABLE_MODELS_FETCH = truthy("VOLTCODE_DISABLE_MODELS_FETCH")
  export const VOLTCODE_DISABLE_CLAUDE_CODE = truthy("VOLTCODE_DISABLE_CLAUDE_CODE")
  export const VOLTCODE_DISABLE_CLAUDE_CODE_PROMPT =
    VOLTCODE_DISABLE_CLAUDE_CODE || truthy("VOLTCODE_DISABLE_CLAUDE_CODE_PROMPT")
  export const VOLTCODE_DISABLE_CLAUDE_CODE_SKILLS =
    VOLTCODE_DISABLE_CLAUDE_CODE || truthy("VOLTCODE_DISABLE_CLAUDE_CODE_SKILLS")
  export const VOLTCODE_FAKE_VCS = process.env["VOLTCODE_FAKE_VCS"]
  export const VOLTCODE_CLIENT = process.env["VOLTCODE_CLIENT"] ?? "cli"
  export const VOLTCODE_MODE = process.env["VOLTCODE_MODE"] ?? "code"
  export const VOLTCODE_SERVER_PASSWORD = process.env["VOLTCODE_SERVER_PASSWORD"]
  export const VOLTCODE_SERVER_USERNAME = process.env["VOLTCODE_SERVER_USERNAME"]

  // Experimental
  export const VOLTCODE_EXPERIMENTAL = truthy("VOLTCODE_EXPERIMENTAL")
  export const VOLTCODE_EXPERIMENTAL_FILEWATCHER = truthy("VOLTCODE_EXPERIMENTAL_FILEWATCHER")
  export const VOLTCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("VOLTCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const VOLTCODE_EXPERIMENTAL_ICON_DISCOVERY =
    VOLTCODE_EXPERIMENTAL || truthy("VOLTCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const VOLTCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("VOLTCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const VOLTCODE_ENABLE_EXA =
    truthy("VOLTCODE_ENABLE_EXA") || VOLTCODE_EXPERIMENTAL || truthy("VOLTCODE_EXPERIMENTAL_EXA")
  export const VOLTCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("VOLTCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const VOLTCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("VOLTCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const VOLTCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("VOLTCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const VOLTCODE_CHUNK_TIMEOUT_MS = number("VOLTCODE_CHUNK_TIMEOUT_MS")
  export const VOLTCODE_EXPERIMENTAL_OXFMT = VOLTCODE_EXPERIMENTAL || truthy("VOLTCODE_EXPERIMENTAL_OXFMT")
  export const VOLTCODE_EXPERIMENTAL_LSP_TY = truthy("VOLTCODE_EXPERIMENTAL_LSP_TY")
  export const VOLTCODE_EXPERIMENTAL_LSP_TOOL = VOLTCODE_EXPERIMENTAL || truthy("VOLTCODE_EXPERIMENTAL_LSP_TOOL")
  export const VOLTCODE_EXPERIMENTAL_PLAN_MODE = VOLTCODE_EXPERIMENTAL || truthy("VOLTCODE_EXPERIMENTAL_PLAN_MODE")
  export const VOLTCODE_EXPERIMENTAL_LCM = truthy("VOLTCODE_EXPERIMENTAL_LCM")
  export const VOLTCODE_LCM_CONTEXT_THRESHOLD = number("VOLTCODE_LCM_CONTEXT_THRESHOLD")
  export const VOLTCODE_LCM_DOLT_TURNS_CAP = number("VOLTCODE_LCM_DOLT_TURNS_CAP")
  export const VOLTCODE_LCM_DOLT_TURNS_SOFT = number("VOLTCODE_LCM_DOLT_TURNS_SOFT")
  export const VOLTCODE_LCM_DOLT_TURNS_DELTA = number("VOLTCODE_LCM_DOLT_TURNS_DELTA")
  export const VOLTCODE_LCM_DOLT_TURNS_TARGET = number("VOLTCODE_LCM_DOLT_TURNS_TARGET")
  export const VOLTCODE_LCM_DOLT_TURNS_FRESH_TAIL_FLOOR = number("VOLTCODE_LCM_DOLT_TURNS_FRESH_TAIL_FLOOR")
  export const VOLTCODE_LCM_DOLT_LEAVES_SOFT = number("VOLTCODE_LCM_DOLT_LEAVES_SOFT")
  export const VOLTCODE_LCM_DOLT_LEAVES_DELTA = number("VOLTCODE_LCM_DOLT_LEAVES_DELTA")
  export const VOLTCODE_LCM_DOLT_LEAVES_TARGET = number("VOLTCODE_LCM_DOLT_LEAVES_TARGET")
  export const VOLTCODE_LCM_DOLT_BINDLES_SOFT = number("VOLTCODE_LCM_DOLT_BINDLES_SOFT")
  export const VOLTCODE_LCM_DOLT_BINDLES_DELTA = number("VOLTCODE_LCM_DOLT_BINDLES_DELTA")
  export const VOLTCODE_LCM_DOLT_BINDLES_TARGET = number("VOLTCODE_LCM_DOLT_BINDLES_TARGET")
  export const VOLTCODE_LCM_DOLT_HARD_LIMIT_RISK_BUFFER = number("VOLTCODE_LCM_DOLT_HARD_LIMIT_RISK_BUFFER")

  // Color depth override: "truecolor" | "256" | "16" | "auto"
  // Use this to force a specific color mode when terminal detection fails
  export const VOLTCODE_COLOR_DEPTH = process.env["VOLTCODE_COLOR_DEPTH"] as
    | "truecolor"
    | "256"
    | "16"
    | "auto"
    | undefined

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
