name: voltcode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  voltcode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /voltcode') ||
      startsWith(github.event.comment.body, '/voltcode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run voltcode
        uses: anomalyco/voltcode/github@latest
        env:
          VOLTCODE_API_KEY: ${{ secrets.VOLTCODE_API_KEY }}
          VOLTCODE_PERMISSION: '{"bash": "deny"}'
        with:
          model: voltcode/claude-opus-4-5
